// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmstiriwubtoqwczbmod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhtc3Rpcml3dWJ0b3F3Y3pibW9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQzMzYzOTEsImV4cCI6MjA5OTkxMjM5MX0.QvEdHVLSYKacWRkbxupoYapQmc03UAL9EaohWkV3DDc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});